name: Get Tool version
description: Read tool4d version parameters from package.json
inputs:
   build_project_name: 
      required: true
      type: string  
outputs:
   platform: 
     value: ${{ steps.get.outputs.platform }}
   branch: 
     value: ${{ steps.get.outputs.branch }}
   version: 
     value: ${{ steps.get.outputs.version }}
   build: 
     value: ${{ steps.get.outputs.build }}  
   arch: 
     value: ${{ steps.get.outputs.arch }} 
     
runs:
  using: "composite"
  steps:      
    run: |
      platform=$(cat ./package.json | jq -r tool.platform)
      echo "platform=${platform}" >> $GITHUB_OUTPUT
      
      branch=$(cat ./package.json | jq -r tool.branch)
      echo "branch=${branch}" >> $GITHUB_OUTPUT
      
      version=$(cat ./package.json | jq -r tool.version)
      echo "version=${version}" >> $GITHUB_OUTPUT
      
      build=$(cat ./build.json | jq -r tool.build)
      echo "build=${build}" >> $GITHUB_OUTPUT
      
      arch=$(cat ./package.json | jq -r tool.arch)
      echo "arch=${arch}" >> $GITHUB_OUTPUT
