name: Run Tests
description: Run unit tests
inputs:
  project_path:
    required: true
    type: string
  startup_method: 
    required: false
    type: string
  skip_onstartup: 
    required: false
    type: boolean  
  create_data: 
    required: false
    type: boolean
  create_data: 
    dataless: false
    type: boolean
