name: Sign App
description: 
inputs:
  sign:
    required: true
    type: string
  keychain:
    required: true
    type: string
  apple_id:
    required: true
    type: string 
  team_id:
    required: true
    type: string 
  password:
    required: true
    type: string 
  path:
    required: true
    type: string 
    
outputs:
  dmg_path: ${{ steps.hdiutil.outputs.dmg_path }}

runs:
  using: "composite"
  steps:
  
    - name: codesign
      id: codesign
      continue-on-error: true
      run: |
        IFS=$'\n'; set -f
        for f in $(find "${path}" -type f \( -perm +111 -o -name "*.dylib" -o -name "*.js" -o -name "*.json" -o -name "*.html" \) | sort -r )
        do codesign --verbose --options=runtime --timestamp --force --sign "#{sign}" --keychain ${keychain}; 
        done
        unset IFS; set +f
      shell: bash  
      env:
        sign: ${{ inputs.sign }}
        keychain: ${{ inputs.keychain }}
        path: ${{ inputs.path }}
        
    - name: hdiutil
      id: hdiutil
      run: |
        DMG_PATH="${path}.dmg"
        rm -f "${DMG_PATH}"
        hdiutil create -format UDBZ -plist -srcfolder "${DMG_PATH}"
        echo "dmg_path=${DMG_PATH}" >> $GITHUB_OUTPUT
      shell: bash  
      env:
        path: ${{ inputs.path }}

    - name: notarytool
      id: notarytool
      run: |
        xcrun notarytool submit "${dmg_path}" --apple-id "${apple_id}" --team-id "${team_id}" --password "${password}"  --wait
      shell: bash  
      env:
        apple_id: ${{ inputs.apple_id }}   
        team_id: ${{ inputs.team_id }}  
        password: ${{ inputs.password }}  
        dmg_path: ${{ steps.hdiutil.outputs.dmg_path }}
