name: Install miyako/4d-class-compiler as Component
description: 
inputs:
   build_project_name: 
      required: true
      type: string  
   platform: 
      required: true
      type: string  
outputs: 
    compiler_component_path:
      value: ${{ steps.setup.outputs.compiler_component_path }}
    
runs:
  using: "composite"
  steps:

  - name: check platform windows
    if: ${{ startsWith(inputs.platform, 'windows') }}
    run: |
      $OutputEncoding = [System.Text.Encoding]::GetEncoding('utf-8')
    shell: pwsh
   
  - id: setup  
    run: |
      echo "compiler_component_path=${BUILD_PROJECT_NAME}/Components/compiler.4dbase" >> $GITHUB_OUTPUT
    shell: bash
    env:  
      BUILD_PROJECT_NAME: ${{ inputs.build_project_name }}

  - name: checkout compiler repo
    uses: actions/checkout@v4
    with:
      repository: miyako/4d-class-compiler
      path: ${{ steps.setup.outputs.compiler_component_path }}
