name: Get Tool Version
description: Read tool4d version parameters from package.json
inputs:
   build_project_name: 
      required: true
      type: string  
outputs:
   platform: 
     value: ${{ steps.get.outputs.platform }}
   branch: 
     value: ${{ steps.get.outputs.branch }}
   version: 
     value: ${{ steps.get.outputs.version }}
   build: 
     value: ${{ steps.get.outputs.build }}  
   arch: 
     value: ${{ steps.get.outputs.arch }} 
     
runs:
  using: "composite"
  steps:   
    - name: get values
      id: get
      run: |
        $json = Get-Content package.json | Out-String | ConvertFrom-Json
        $platform = $json.tool.platform
        $branch = $json.tool.branch
        $version = $json.tool.version
        $build = $json.tool.build
        $arch = $json.tool.arch   
        [System.IO.File]::AppendAllText($env:GITHUB_OUTPUT, "platform="+$platform+"\n")
        [System.IO.File]::AppendAllText($env:GITHUB_OUTPUT, "branch="+$branch+"\n")
        [System.IO.File]::AppendAllText($env:GITHUB_OUTPUT, "version="+$version+"\n")
        [System.IO.File]::AppendAllText($env:GITHUB_OUTPUT, "build="+$build+"\n")
        [System.IO.File]::AppendAllText($env:GITHUB_OUTPUT, "arch="+$arch+"\n")
        Get-Content $env:GITHUB_OUTPUT
      shell: powershell
