name: Get Tool Version
description: Read tool4d version parameters from package.json
inputs:
   build_project_name: 
      required: true
      type: string  
outputs:
   platform: 
     value: ${{ steps.get.outputs.platform }}
   branch: 
     value: ${{ steps.get.outputs.branch }}
   version: 
     value: ${{ steps.get.outputs.version }}
   build: 
     value: ${{ steps.get.outputs.build }}  
   arch: 
     value: ${{ steps.get.outputs.arch }} 
     
runs:
  using: "composite"
  steps:   
    - name: get values
      id: get
      run: |
        $path = Join-Path $env:GITHUB_WORKSPACE "package.json"
        $json = Get-Content $path | Out-String | ConvertFrom-Json
        $platform = $json.tool.platform
        $branch = $json.tool.branch
        $version = $json.tool.version
        $build = $json.tool.build
        $arch = $json.tool.arch     
        [System.IO.File]::AppendAllText($env:GITHUB_OUTPUT, "platform=$($env:platform)`n")
        [System.IO.File]::AppendAllText($env:GITHUB_OUTPUT, "branch=$($env:branch)`n")
        [System.IO.File]::AppendAllText($env:GITHUB_OUTPUT, "version=$($env:version)`n")
        [System.IO.File]::AppendAllText($env:GITHUB_OUTPUT, "build=$($env:build)`n")
        [System.IO.File]::AppendAllText($env:GITHUB_OUTPUT, "arch=$($env:arch)`n")
      shell: powershell
      
    - name: check version env
      run: echo "env is ${{ env.version }}"
      shell: powershell
      
    - name: check version step
      run: echo "output is ${{ steps.get.outputs.version }}"
      shell: powershell
