name: Set Package Version
description: Write updated version code to package.json
inputs:
   mode: 
     required: true
     type: string
outputs:
   version:
     value: ${{ steps.set.outputs.version }}
   mode:
     value: ${{ inputs.mode }}

runs:
  using: "composite"
  steps:   
    
    - name: git config 
      run: |
        git config --local user.name "GitHub Action"
        git config --local user.email "action@github.com"  
      shell: bash
      
    - name: major
      if: ${{ inputs.mode == 'major' }} 
      run: |
        npm version major
      shell: bash
      
    - name: minor
      if: ${{ inputs.mode == 'minor' }} 
      run: |
        npm version minor
      shell: bash
      
    - name: patch
      if: ${{ inputs.mode == 'patch' }} 
      run: |
        npm version patch
      shell: bash
      
    - name: git push
      run: |
        git push origin
      shell: bash
      
    - id: set
      run: |
        version=`cat package.json | jq -r '.version'`
        echo "version=${version}" >> $GITHUB_OUTPUT
      shell: bash  
